config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get '/tasks/:id', to: 'tasks#show', as: :task
  get '/task/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save # Will raise ActiveModel::ForbiddenAttributesError
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params) # Will raise ActiveModel::ForbiddenAttributesError
    # redirect_to tasks_path
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1 class="mb-3">Tasks List</h1>
<table>
  <tr class="text-center">
    <th>Status</th>
    <th>Title</th>
    <th>Delete?</th>
  </tr>
  <% @tasks.each do |task| %>
  <tr class="text-center">
    <td><input type="checkbox" <%= 'checked' if task.completed %>></td>
    <td><label><%= link_to task.title, task_path(task), class: "text-decoration-none" %></label></td>
    <td><label><%= link_to "🗑️", task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></label></td>
    <% end %>
  </tr>
</table>
  <%= link_to 'Create a new task', '/tasks/new', class: 'btn btn-success m-3' %>

app/views/tasks/new.html.erb
  <%= form_with model: @task do |f| %>
  <div class="card">
    <div class="card-body">

    <div class="mb-3">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="mb-3">
    <%= f.label :details %>
    <%= f.text_field :details %>
    </div>

    <%= f.submit %>
  <% end %>
  </div>
  </div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to 'Edit', edit_task_path, class: 'btn btn-primary m-3' %><br>
<%= link_to 'Back', tasks_path, class: 'btn btn-primary m-3' %>